import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import Header from "../common/header/page";
import Footer from "../common/footer/page";
const navLinks = [
  { name: "Register", href: "/register" },
  {
    name: "Login",
    href: "/login",
  },
  { name: "Forgot Password", href: "/forgot-password" },
];
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "abouts",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon-32x32.png" sizes="any" />

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {navLinks.map((i, index) => {
          return (
            <Link href={i.href} key={index}>
              {i.name}
            </Link>
          );
        })}
        {children}
        <Footer />
      </body>
    </html>
  );
}
